### PR TITLE
update to use A5 to include soup

### PR DESCRIPTION
**Pull request by mchv**

### CODE REVIEW

**Review by desbo — APPROVED** [review]
👋

**Review by gtrufitt — APPROVED** [review]
VERY IMPORTANT 

tenor-10746541
tenor-201110251

**Comment by mchv** [comment]
@desbo thanks! Do you remember what credentials did you put in `credentials.json`? I have tried using the service account key id but it crashes.

**Comment by mchv** [comment]
Figure out I don't have any other options than create new credentials. There is clearly work to do to automate deployment to store and retrieve credentials safely.

**Comment by desbo** [comment]
I think the ones it was using before are in the app's cloud storage bucket

**Pull request merged**
